CHANGELOG.md
gradle.properties

See https://github.com/a-sit-plus/vck/pull/180

Fix ISO presentations

---

CHANGELOG.md
build.gradle.kts
shared/build.gradle.kts

made conventions more flexible to remove the ugly xcf export mess; tested locally and successfully built the ios app

fix xcf export mess

---

CHANGELOG.md
gradle/libs.versions.toml
shared/build.gradle.kts

pending https://github.com/a-sit-plus/mobile-driving-licence-credential/pull/10

Update all Credentials

---

shared/src/commonMain/kotlin/ui/viewmodels/Authentication/AuthenticationSelectionViewModel.kt

closes https://github.com/a-sit-plus/valera/issues/158

Actually filter the selection during authentication

---

shared/src/commonMain/kotlin/ui/navigation/WalletNavigation.kt

closes https://github.com/a-sit-plus/valera/issues/159

Fix crash during provisioning

---

CHANGELOG.md
androidApp/src/androidMain/kotlin/at/asitplus/wallet/app/android/MainActivity.kt
gradle/libs.versions.toml
iosApp/iosApp/ContentView.swift
shared/src/androidMain/kotlin/main.android.kt
shared/src/commonMain/composeResources/values-de/strings.xml
shared/src/commonMain/composeResources/values-en/strings.xml
shared/src/commonMain/composeResources/values/strings.xml
shared/src/commonMain/kotlin/App.kt
shared/src/commonMain/kotlin/at/asitplus/wallet/app/common/BuildContext.kt
shared/src/commonMain/kotlin/at/asitplus/wallet/app/common/HttpService.kt
shared/src/commonMain/kotlin/at/asitplus/wallet/app/common/SnackbarService.kt
shared/src/commonMain/kotlin/at/asitplus/wallet/app/common/WalletMain.kt
shared/src/commonMain/kotlin/at/asitplus/wallet/app/common/dcapi/IdentityCredentialField.kt
shared/src/commonMain/kotlin/ui/navigation/IntentHandler.kt
shared/src/commonMain/kotlin/ui/navigation/WalletNavigation.kt

This is useful for Android installations, as we are not distributing over any app store.

Add update check on app start

---

.github/workflows/test-ios.yml
androidApp/src/androidMain/kotlin/at/asitplus/wallet/app/android/MainActivity.kt
iosApp/iosApp/ContentView.swift
shared/src/commonMain/kotlin/at/asitplus/wallet/app/common/BuildContext.kt
shared/src/commonMain/kotlin/at/asitplus/wallet/app/common/HttpService.kt
shared/src/commonMain/kotlin/at/asitplus/wallet/app/common/WalletMain.kt
shared/src/commonTest/kotlin/InstrumentedTestsSuite.kt

User Agent Header

---

CHANGELOG.md
gradle.properties

Release 5.4.11

---

CHANGELOG.md
shared/src/commonMain/composeResources/values-de/strings.xml
shared/src/commonMain/composeResources/values-en/strings.xml
shared/src/commonMain/composeResources/values/strings.xml
shared/src/commonMain/kotlin/at/asitplus/wallet/app/common/Extensions.kt
shared/src/commonMain/kotlin/at/asitplus/wallet/app/common/thirdParty/at/asitplus/jsonpath/core/NormalizedJsonPath.kt
shared/src/commonMain/kotlin/at/asitplus/wallet/app/common/thirdParty/kotlinx/serialization/json/JsonElement.kt
shared/src/commonMain/kotlin/ui/composables/PresentationRequestPreview.kt
shared/src/commonMain/kotlin/ui/navigation/WalletNavigation.kt
shared/src/commonMain/kotlin/ui/viewmodels/authentication/AuthenticationConsentViewModel.kt
shared/src/commonMain/kotlin/ui/viewmodels/authentication/AuthenticationSelectionPresentationExchangeViewModel.kt
shared/src/commonMain/kotlin/ui/viewmodels/authentication/AuthenticationViewModel.kt
shared/src/commonMain/kotlin/ui/viewmodels/authentication/DCAPIAuthenticationViewModel.kt
shared/src/commonMain/kotlin/ui/viewmodels/authentication/DefaultAuthenticationViewModel.kt
shared/src/commonMain/kotlin/ui/views/Authentication/AuthenticationConsentView.kt
shared/src/commonMain/kotlin/ui/views/Authentication/AuthenticationSelectionPresentationExchangeView.kt
shared/src/commonMain/kotlin/ui/views/Authentication/AuthenticationView.kt

Implements the consent preview screen

Add: DCQL Request Preview

---

CHANGELOG.md
gradle.properties
iosApp/iosApp.xcodeproj/project.pbxproj
iosApp/iosApp/Info.plist
shared/src/commonMain/kotlin/at/asitplus/wallet/app/common/Extensions.kt
shared/src/commonMain/kotlin/at/asitplus/wallet/app/common/ProvisioningService.kt
shared/src/commonMain/kotlin/at/asitplus/wallet/app/common/WalletMain.kt
shared/src/commonMain/kotlin/data/credentials/CredentialAdapter.kt
shared/src/commonMain/kotlin/ui/navigation/WalletNavigation.kt
shared/src/commonMain/kotlin/ui/viewmodels/authentication/AuthenticationConsentViewModel.kt
shared/src/commonMain/kotlin/ui/viewmodels/authentication/AuthenticationViewModel.kt
shared/src/commonMain/kotlin/ui/viewmodels/authentication/DefaultAuthenticationViewModel.kt
shared/src/commonMain/kotlin/ui/viewmodels/authentication/PresentationViewModel.kt
shared/src/commonMain/kotlin/ui/views/Authentication/AuthenticationConsentView.kt

@n0900 Are those changes correct, for your changes of `TransactionData` in VC-K?

Update to VC-K 5.5.1

---

CHANGELOG.md
gradle.properties
iosApp/iosApp.xcodeproj/project.pbxproj
iosApp/iosApp/Info.plist
shared/src/commonMain/kotlin/at/asitplus/wallet/app/common/Extensions.kt
shared/src/commonMain/kotlin/at/asitplus/wallet/app/common/ProvisioningService.kt
shared/src/commonMain/kotlin/at/asitplus/wallet/app/common/WalletMain.kt
shared/src/commonMain/kotlin/data/Attribute.kt
shared/src/commonMain/kotlin/data/credentials/CredentialAdapter.kt
shared/src/commonMain/kotlin/ui/composables/AttributeRepresentation.kt
shared/src/commonMain/kotlin/ui/composables/DCQLCredentialQuerySubmissionSelection.kt
shared/src/commonMain/kotlin/ui/composables/DCQLCredentialQuerySubmissionSelectionOption.kt
shared/src/commonMain/kotlin/ui/navigation/WalletNavigation.kt
shared/src/commonMain/kotlin/ui/viewmodels/authentication/AuthenticationConsentViewModel.kt
shared/src/commonMain/kotlin/ui/viewmodels/authentication/AuthenticationSelectionDCQLView.kt
shared/src/commonMain/kotlin/ui/viewmodels/authentication/AuthenticationViewModel.kt
shared/src/commonMain/kotlin/ui/viewmodels/authentication/DefaultAuthenticationViewModel.kt
shared/src/commonMain/kotlin/ui/viewmodels/authentication/PresentationViewModel.kt
shared/src/commonMain/kotlin/ui/views/Authentication/AuthenticationConsentView.kt
shared/src/commonMain/kotlin/ui/views/Authentication/AuthenticationView.kt

Tested as https://apps.egiz.gv.at/customverifier/por.html
E.g. shows attribute names for SD-JWT without disclosures (e.g. Power of Representation)

Fix DCQL for SD-JWT

---

shared/src/commonMain/kotlin/at/asitplus/wallet/app/common/ProvisioningService.kt
shared/src/commonMain/kotlin/at/asitplus/wallet/app/common/SigningService.kt
shared/src/commonMain/kotlin/at/asitplus/wallet/app/common/WalletMain.kt
shared/src/commonMain/kotlin/ui/navigation/IntentService.kt

- Reduce complexity
- IntentService now responsible for both directions of an intent

Improve intent handling

---

shared/src/commonMain/kotlin/ui/composables/LabeledAttributeCheckbox.kt
shared/src/commonMain/kotlin/ui/composables/credentials/AttributeSelectionGroup.kt

- Disable selection of non disclosable attributes

Improve AttributeSelectionGroup

---

shared/build.gradle.kts

Fix build error with iOS Simulator

---

shared/src/commonMain/kotlin/ui/composables/CustomFloatingActionMenu.kt

Match provisioning buttons

---

androidApp/src/androidMain/kotlin/at/asitplus/wallet/app/android/NdefDeviceEngagementService.kt
shared/src/androidInstrumentedTest/kotlin/InstrumentedTests.android.kt
shared/src/androidMain/kotlin/main.android.kt
shared/src/androidUnitTest/kotlin/InstrumentedTests.android.kt
shared/src/commonMain/kotlin/at/asitplus/wallet/app/common/WalletMain.kt
shared/src/commonMain/kotlin/ui/viewmodels/authentication/PresentationStateModel.kt
shared/src/commonMain/kotlin/ui/viewmodels/iso/ShowQrCodeViewModel.kt
shared/src/commonTest/kotlin/InstrumentedTestsSuite.kt
shared/src/iosMain/kotlin/main.ios.kt

Adds a default exception handler to all coroutines started from our CoroutineContext.
Also fixes crashes in multipaz's Bluetooth code

Coroutine error handling

---

shared/src/androidMain/kotlin/main.android.kt
shared/src/commonMain/kotlin/at/asitplus/wallet/app/common/dcapi/DCAPIExportService.kt
shared/src/commonMain/kotlin/data/credentials/CredentialAdapter.kt
shared/src/commonMain/kotlin/ui/viewmodels/authentication/DCAPIAuthenticationViewModel.kt

Prevents silent errors when registering loaded credentials with DCAPI

DCAPI Credential Loading

---

CHANGELOG.md
gradle.properties
iosApp/iosApp/Info.plist
shared/src/commonMain/composeResources/values-de/strings.xml
shared/src/commonMain/kotlin/at/asitplus/wallet/app/common/ErrorService.kt
shared/src/commonMain/kotlin/at/asitplus/wallet/app/common/Extensions.kt
shared/src/commonMain/kotlin/ui/navigation/WalletNavigation.kt
shared/src/commonMain/kotlin/ui/viewmodels/authentication/AuthenticationSelectionPresentationExchangeViewModel.kt

Fixes small bugs from release 5.6.0
VC-K 5.6.1 Snapshot will be published soon

VC-K 5.6.1

---

shared/src/commonMain/kotlin/ui/composables/ScreenHeading.kt
shared/src/commonMain/kotlin/ui/views/CredentialDetailsView.kt
shared/src/commonMain/kotlin/ui/views/CredentialsView.kt
shared/src/commonMain/kotlin/ui/views/ErrorView.kt
shared/src/commonMain/kotlin/ui/views/GenericQrCodeScannerView.kt
shared/src/commonMain/kotlin/ui/views/LoadingView.kt
shared/src/commonMain/kotlin/ui/views/LogView.kt
shared/src/commonMain/kotlin/ui/views/OnboardingInformationView.kt
shared/src/commonMain/kotlin/ui/views/PresentDataView.kt
shared/src/commonMain/kotlin/ui/views/SettingsView.kt
shared/src/commonMain/kotlin/ui/views/authentication/AuthenticationConsentView.kt
shared/src/commonMain/kotlin/ui/views/iso/ShowQrCodeView.kt
shared/src/commonMain/kotlin/ui/views/iso/verifier/VerifierCustomSelectionView.kt
shared/src/commonMain/kotlin/ui/views/iso/verifier/VerifierDocumentSelectionView.kt

Change headline to medium (think iPhone SE!)

---

shared/src/commonMain/composeResources/values-de/strings.xml
shared/src/commonMain/composeResources/values-en/strings.xml
shared/src/commonMain/kotlin/data/credentials/HealthIdCredentialAttributeTranslator.kt
shared/src/commonMain/kotlin/data/document/RequestDocumentBuilder.kt
shared/src/commonMain/kotlin/ui/viewmodels/iso/VerifierViewModel.kt
shared/src/commonMain/kotlin/ui/views/iso/verifier/VerifierCustomSelectionView.kt
shared/src/commonMain/kotlin/ui/views/iso/verifier/VerifierDocumentSelectionView.kt
shared/src/commonMain/kotlin/ui/views/iso/verifier/VerifierPresentationView.kt

Solve issue https://github.com/a-sit-plus/valera/issues/267
- Add `HealthID` for document selection with a predefined subset of attributes
- Add `HealthID` for custom document requests
- Refactoring using `CredentialScheme` and mappings for translation and preselection
<p float="left">
</p>

Proximity: add credentials

---

shared/build.gradle.kts
shared/src/commonMain/kotlin/at/asitplus/wallet/app/common/DocumentProcessing.kt

Revert "update to latest signum"

---

CHANGELOG.md
shared/src/commonMain/kotlin/at/asitplus/wallet/app/common/Extensions.kt
shared/src/commonMain/kotlin/at/asitplus/wallet/app/common/ProvisioningService.kt
shared/src/commonMain/kotlin/data/credentials/MobileDrivingLicenceCredentialAdapter.kt
shared/src/commonMain/kotlin/ui/composables/credentials/AttributeSelectionGroup.kt

Will also need to include https://github.com/a-sit-plus/vck/pull/307

Vilnius Interop Fixes

---

shared/src/commonMain/kotlin/at/asitplus/wallet/app/common/Extensions.kt
shared/src/commonMain/kotlin/ui/composables/PresentationRequestPreview.kt

Fix: DCQL Credential matching for some common jwt claims

---

shared/src/commonMain/kotlin/at/asitplus/wallet/app/common/Extensions.kt

Please merge at your discretion

Fix DCQL over DCAPI

---

shared/src/androidMain/kotlin/at/asitplus/wallet/app/android/dcapi/IdentityCredentialHelper.kt
shared/src/commonMain/kotlin/at/asitplus/wallet/app/common/WalletMain.kt
shared/src/commonMain/kotlin/at/asitplus/wallet/app/common/dcapi/DCAPIExportService.kt
shared/src/commonMain/kotlin/at/asitplus/wallet/app/common/domain/platform/ImageDecoder.kt
shared/src/commonMain/kotlin/data/credentials/EuPidCredentialAdapter.kt
shared/src/commonMain/kotlin/data/credentials/Extensions.kt
shared/src/commonMain/kotlin/data/credentials/IdAustriaCredentialAdapter.kt
shared/src/commonMain/kotlin/data/credentials/MobileDrivingLicenceCredentialAdapter.kt
shared/src/commonMain/kotlin/ui/composables/DCQLCredentialQuerySubmissionSelection.kt
shared/src/commonMain/kotlin/ui/composables/DCQLCredentialQuerySubmissionSelectionOption.kt
shared/src/commonMain/kotlin/ui/composables/credentials/CredentialCard.kt
shared/src/commonMain/kotlin/ui/composables/credentials/CredentialSelectionCard.kt
shared/src/commonMain/kotlin/ui/composables/credentials/CredentialSelectionGroup.kt
shared/src/commonMain/kotlin/ui/composables/credentials/CredentialSummaryCardContent.kt
shared/src/commonMain/kotlin/ui/composables/credentials/EuPidCredentialSummaryCardContent.kt
shared/src/commonMain/kotlin/ui/composables/credentials/EuPidCredentialView.kt
shared/src/commonMain/kotlin/ui/composables/credentials/IdAustriaCredentialSummaryCardContent.kt
shared/src/commonMain/kotlin/ui/composables/credentials/IdAustriaCredentialView.kt
shared/src/commonMain/kotlin/ui/composables/credentials/MobileDrivingLicenceCredentialSummaryCardContent.kt
shared/src/commonMain/kotlin/ui/composables/credentials/MobileDrivingLicenceCredentialView.kt
shared/src/commonMain/kotlin/ui/viewmodels/CredentialDetailsViewModel.kt
shared/src/commonMain/kotlin/ui/viewmodels/CredentialsViewModel.kt
shared/src/commonMain/kotlin/ui/viewmodels/authentication/AuthenticationSelectionDCQLView.kt
shared/src/commonMain/kotlin/ui/views/CredentialDetailsView.kt
shared/src/commonMain/kotlin/ui/views/authentication/AuthenticationSelectionPresentationExchangeView.kt
shared/src/commonMain/kotlin/ui/views/authentication/AuthenticationView.kt
shared/src/commonMain/kotlin/ui/views/iso/verifier/VerifierPresentationView.kt

Don't crash app if decoding fails

Catch decoding failure

---

shared/src/commonMain/kotlin/at/asitplus/wallet/app/common/KeystoreProvider.kt
shared/src/commonMain/kotlin/at/asitplus/wallet/app/common/WalletMain.kt

Closing https://github.com/a-sit-plus/valera/issues/327

Clear key material on reset

---

CHANGELOG.md
shared/src/commonMain/kotlin/ui/composables/credentials/GenericCredentialSummaryCardContent.kt

Credentials: Improve technical details view

---

build.gradle.kts
gradle.properties
settings.gradle.kts
shared/src/commonMain/kotlin/ui/viewmodels/authentication/AuthenticationSelectionPresentationExchangeViewModel.kt
shared/src/commonMain/kotlin/ui/viewmodels/authentication/AuthenticationViewModel.kt

cleans up composite build and off imports. requires https://github.com/a-sit-plus/vck/pull/360 for full glory.
don't press me about the iffy imports!

cleanup composite build
